import Head from "next/head";

export default function Home() {
  const structuredData = {
    "@context": "https://schema.org/",
    "@type": "JobPosting",
    title: "Software Engineer",
    description:
      "<p>Google aspires to be an organization that reflects the globally diverse audience that our products and technology serve. We believe that in addition to hiring the best talent, a diversity of perspectives, ideas and cultures leads to the creation of better products and services.</p>",
    identifier: {
      "@type": "PropertyValue",
      name: "Google",
      value: "1234567",
    },
    datePosted: "2017-01-18",
    validThrough: "2017-03-18T00:00",
    employmentType: "CONTRACTOR",
    hiringOrganization: {
      "@type": "Organization",
      name: "Google",
      sameAs: "https://www.google.com",
      logo: "https://www.example.com/images/logo.png",
    },
    jobLocation: {
      "@type": "Place",
      address: {
        "@type": "PostalAddress",
        streetAddress: "1600 Amphitheatre Pkwy",
        addressLocality: "Mountain View",
        addressRegion: "CA",
        postalCode: "94043",
        addressCountry: "US",
      },
    },
    baseSalary: {
      "@type": "MonetaryAmount",
      currency: "USD",
      value: {
        "@type": "QuantitativeValue",
        value: 40.0,
        unitText: "HOUR",
      },
    },
  };
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="google-site-verification"
          content="AYzbPzE0MLDVwfuRjXbyTnnpfgynKhloPuMuDPXi9t4"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
        />
      </Head>
      <main>Home Page</main>
    </>
  );
}
